== policy/access

=== AccessReport

Represents any access made by the user.

==== Example

[source,json]
----
{
  "action": "Accept",
  "enforcerID": "xxx-xxx-xxx",
  "enforcerNamespace": "/my/namespace",
  "processingUnitID": "xxx-xxx-xxx-xxx",
  "processingUnitName": "pu1",
  "processingUnitNamespace": "/my/ns",
  "type": "SSHLogin"
}
----

==== Relations

===== `POST /accessreports`

Create an access report.

==== Attributes

===== `action` `enum(Accept | Reject)` [`required`]

Action applied to the access.

===== `claimHash` `string`

Hash of the claims used to communicate.

===== `enforcerID` `string` [`required`]

Identifier of the defender.

===== `enforcerNamespace` `string` [`required`]

Namespace of the defender.

===== `processingUnitID` `string`

ID of the processing unit of the report.

===== `processingUnitName` `string`

Name of the processing unit of the report.

===== `processingUnitNamespace` `string`

Namespace of the processing unit of the report.

===== `reason` `string`

This field is only set if `action` is set to `Reject`. It specifies the
reason for the rejection.

===== `timestamp` `time`

Date of the report.

===== `type` `enum(SSHLogin | SSHLogout | SudoEnter | SudoExit)` [`required`]

Type of the report.

=== UserAccessPolicy

The defender policy that controls user access.

==== Example

[source,json]
----
{
  "disabled": false,
  "name": "the name",
  "propagate": false,
  "protected": false
}
----

==== Relations

===== `GET /useraccesspolicies`

Retrieves the list of user access policies.

Parameters:

* `q` (`string`): Filtering query. Consequent `q` parameters will form
an or.
* `propagated` (`boolean`): Also retrieve the objects that propagate
down.

===== `POST /useraccesspolicies`

Creates a new defender policy.

===== `DELETE /useraccesspolicies/:id`

Deletes the policy with the given ID.

Parameters:

* `q` (`string`): Filtering query. Consequent `q` parameters will form
an or.

===== `GET /useraccesspolicies/:id`

Retrieves the policy with the given ID.

Parameters:

* `propagated` (`boolean`): Also retrieve the objects that propagate
down.

===== `PUT /useraccesspolicies/:id`

Updates the policy with the given ID.

==== Attributes

===== `ID` `string` [`identifier`,`autogenerated`,`read_only`]

Identifier of the object.

===== `activeDuration` `string` [`format=^[0-9]+[smh]$`]

Defines for how long the policy will be active according to the
`activeSchedule`.

===== `activeSchedule` `string`

Defines when the policy should be active using the cron notation. The
policy will be active for the given `activeDuration`.

===== `allowedSudoUsers` `[]string`

Indicates the list of user who can use `sudo` commands.

===== `annotations` `map[string][]string`

Stores additional information about an entity.

===== `associatedTags` `[]string`

List of tags attached to an entity.

===== `createTime` `time` [`autogenerated`,`read_only`]

Creation date of the object.

===== `description` `string` [`max_length=1024`]

Description of the object.

===== `disabled` `boolean`

Defines if the property is disabled.

===== `expirationTime` `time`

If set the policy will be automatically deleted after the given time.

===== `metadata` `[]string` [`creation_only`]

Contains tags that can only be set during creation, must all start with
the `@' prefix, and should only be used by external systems.

===== `name` `string` [`required`,`max_length=256`]

Name of the entity.

===== `namespace` `string` [`autogenerated`,`read_only`]

Namespace tag attached to an entity.

===== `normalizedTags` `[]string` [`autogenerated`,`read_only`]

Contains the list of normalized tags of the entities.

===== `object` `[][]string`

Contains the tag expression matching the defenders the subject is
allowed to connect to.

===== `propagate` `boolean`

Propagates the policy to all of its children.

===== `protected` `boolean`

Defines if the object is protected.

===== `subject` `[][]string`

Contains the tag expression the tags need to match for the policy to
apply.

===== `updateTime` `time` [`autogenerated`,`read_only`]

Last update date of the object.
