== core/enforcer

=== CounterReport

Post a new counter tracing report.

==== Example

[source,json]
----
{
  "AckInUnknownState": 0,
  "AckInvalidFormat": 0,
  "AckRejected": 0,
  "AckSigValidationFailed": 0,
  "AckTCPNoTCPAuthOption": 0,
  "ConnectionsProcessed": 0,
  "ContextIDNotFound": 0,
  "DroppedExternalService": 0,
  "InvalidConnState": 0,
  "InvalidNetState": 0,
  "InvalidProtocol": 0,
  "InvalidSynAck": 0,
  "MarkNotFound": 0,
  "NetSynNotSeen": 0,
  "NoConnFound": 0,
  "NonPUTraffic": 0,
  "OutOfOrderSynAck": 0,
  "PortNotFound": 0,
  "RejectPacket": 0,
  "ServicePostprocessorFailed": 0,
  "ServicePreprocessorFailed": 0,
  "SynAckBadClaims": 0,
  "SynAckClaimsMisMatch": 0,
  "SynAckDroppedExternalService": 0,
  "SynAckInvalidFormat": 0,
  "SynAckMissingClaims": 0,
  "SynAckMissingToken": 0,
  "SynAckNoTCPAuthOption": 0,
  "SynAckRejected": 0,
  "SynDroppedInvalidFormat": 0,
  "SynDroppedInvalidToken": 0,
  "SynDroppedNoClaims": 0,
  "SynDroppedTCPOption": 0,
  "SynRejectPacket": 0,
  "SynUnexpectedPacket": 0,
  "TCPAuthNotFound": 0,
  "UDPAckInvalidSignature": 0,
  "UDPConnectionsProcessed": 0,
  "UDPDropContextNotFound": 0,
  "UDPDropFin": 0,
  "UDPDropInNfQueue": 0,
  "UDPDropNoConnection": 0,
  "UDPDropPacket": 0,
  "UDPDropQueueFull": 0,
  "UDPDropSynAck": 0,
  "UDPInvalidNetState": 0,
  "UDPPostProcessingFailed": 0,
  "UDPPreProcessingFailed": 0,
  "UDPRejected": 0,
  "UDPSynAckDropBadClaims": 0,
  "UDPSynAckMissingClaims": 0,
  "UDPSynAckPolicy": 0,
  "UDPSynDrop": 0,
  "UDPSynDropPolicy": 0,
  "UDPSynInvalidToken": 0,
  "UDPSynMissingClaims": 0,
  "UnknownError": 0,
  "connectionsAnalyzed": 0,
  "connectionsDropped": 0,
  "connectionsExpired": 0,
  "droppedPackets": 0,
  "encryptionFailures": 0,
  "enforcerID": "xxxx-xxx-xxxx",
  "enforcerNamespace": "/my/namespace",
  "externalNetworkConnections": 0,
  "policyDrops": 0,
  "processingUnitID": "xxx-xxx-xxx",
  "processingUnitNamespace": "/my/namespace",
  "timestamp": "2018-06-14T23:10:46.420397985Z",
  "tokenDrops": 0
}
----

==== Relations

===== `POST /counterreports`

Create a counter report.

==== Attributes

===== `AckInUnknownState` `integer`

Counter for sending FIN ACK received in unknown connection state.

Default value:

[source,json]
----
0
----

===== `AckInvalidFormat` `integer`

Counter for ACK packet dropped because of invalid format.

Default value:

[source,json]
----
0
----

===== `AckRejected` `integer`

Counter for ACK packets rejected as per policy.

Default value:

[source,json]
----
0
----

===== `AckSigValidationFailed` `integer`

Counter for ACK packet dropped because signature validation failed.

Default value:

[source,json]
----
0
----

===== `AckTCPNoTCPAuthOption` `integer`

Counter for TCP authentication option not found.

Default value:

[source,json]
----
0
----

===== `ConnectionsProcessed` `integer`

Counter for connections processed.

Default value:

[source,json]
----
0
----

===== `ContextIDNotFound` `integer`

Counter for unable to find ContextID.

Default value:

[source,json]
----
0
----

===== `DroppedExternalService` `integer`

Counter for no ACLs found for external services. Dropping application
SYN packet.

Default value:

[source,json]
----
0
----

===== `InvalidConnState` `integer`

Counter for invalid connection state.

Default value:

[source,json]
----
0
----

===== `InvalidNetState` `integer`

Counter for invalid net state.

Default value:

[source,json]
----
0
----

===== `InvalidProtocol` `integer`

Counter for invalid protocol.

Default value:

[source,json]
----
0
----

===== `InvalidSynAck` `integer`

Counter for processing unit is already dead - drop SYN ACK packet.

Default value:

[source,json]
----
0
----

===== `MarkNotFound` `integer`

Counter for processing unit mark not found.

Default value:

[source,json]
----
0
----

===== `NetSynNotSeen` `integer`

Counter for network SYN packet was not seen.

Default value:

[source,json]
----
0
----

===== `NoConnFound` `integer`

Counter for no context or connection found.

Default value:

[source,json]
----
0
----

===== `NonPUTraffic` `integer`

Counter for traffic that belongs to a non-processing unit process.

Default value:

[source,json]
----
0
----

===== `OutOfOrderSynAck` `integer`

Counter for SYN ACK for flow with processed FIN ACK.

Default value:

[source,json]
----
0
----

===== `PortNotFound` `integer`

Counter for port not found.

Default value:

[source,json]
----
0
----

===== `RejectPacket` `integer`

Counter for reject the packet as per policy.

Default value:

[source,json]
----
0
----

===== `ServicePostprocessorFailed` `integer`

Counter for post service processing failed for network packet.

Default value:

[source,json]
----
0
----

===== `ServicePreprocessorFailed` `integer`

Counter for network packets that failed preprocessing.

Default value:

[source,json]
----
0
----

===== `SynAckBadClaims` `integer`

Counter for SYN ACK packet dropped because of bad claims.

Default value:

[source,json]
----
0
----

===== `SynAckClaimsMisMatch` `integer`

Counter for SYN ACK packet dropped because of encryption mismatch.

Default value:

[source,json]
----
0
----

===== `SynAckDroppedExternalService` `integer`

Counter for SYN ACK from external service dropped.

Default value:

[source,json]
----
0
----

===== `SynAckInvalidFormat` `integer`

Counter for SYN ACK packet dropped because of invalid format.

Default value:

[source,json]
----
0
----

===== `SynAckMissingClaims` `integer`

Counter for SYN ACK packet dropped because of no claims.

Default value:

[source,json]
----
0
----

===== `SynAckMissingToken` `integer`

Counter for SYN ACK packet dropped because of missing token.

Default value:

[source,json]
----
0
----

===== `SynAckNoTCPAuthOption` `integer`

Counter for TCP authentication option not found.

Default value:

[source,json]
----
0
----

===== `SynAckRejected` `integer`

Counter for dropping because of reject rule on transmitter.

Default value:

[source,json]
----
0
----

===== `SynDroppedInvalidFormat` `integer`

Counter for SYN packet dropped because of invalid format.

Default value:

[source,json]
----
0
----

===== `SynDroppedInvalidToken` `integer`

Counter for SYN packet dropped because of invalid token.

Default value:

[source,json]
----
0
----

===== `SynDroppedNoClaims` `integer`

Counter for SYN packet dropped because of no claims.

Default value:

[source,json]
----
0
----

===== `SynDroppedTCPOption` `integer`

Counter for TCP authentication option not found.

Default value:

[source,json]
----
0
----

===== `SynRejectPacket` `integer`

Counter for SYN packet dropped due to policy.

Default value:

[source,json]
----
0
----

===== `SynUnexpectedPacket` `integer`

Counter for received SYN packet from unknown processing unit.

Default value:

[source,json]
----
0
----

===== `TCPAuthNotFound` `integer`

Counter for TCP authentication option not found.

Default value:

[source,json]
----
0
----

===== `UDPAckInvalidSignature` `integer`

Counter for UDP ACK packet dropped due to an invalid signature.

Default value:

[source,json]
----
0
----

===== `UDPConnectionsProcessed` `integer`

Counter for number of processed UDP connections.

Default value:

[source,json]
----
0
----

===== `UDPDropContextNotFound` `integer`

Counter for dropped UDP data packets with no context.

Default value:

[source,json]
----
0
----

===== `UDPDropFin` `integer`

Counter for dropped UDP FIN handshake packets.

Default value:

[source,json]
----
0
----

===== `UDPDropInNfQueue` `integer`

Counter for dropped UDP in NfQueue.

Default value:

[source,json]
----
0
----

===== `UDPDropNoConnection` `integer`

Counter for dropped UDP data packets with no connection.

Default value:

[source,json]
----
0
----

===== `UDPDropPacket` `integer`

Counter for dropped UDP data packets.

Default value:

[source,json]
----
0
----

===== `UDPDropQueueFull` `integer`

Counter for dropped UDP Queue Full.

Default value:

[source,json]
----
0
----

===== `UDPDropSynAck` `integer`

Counter for dropped UDP SYN ACK handshake packets.

Default value:

[source,json]
----
0
----

===== `UDPInvalidNetState` `integer`

Counter for UDP packets received in invalid network state.

Default value:

[source,json]
----
0
----

===== `UDPPostProcessingFailed` `integer`

Counter for UDP packets failing postprocessing.

Default value:

[source,json]
----
0
----

===== `UDPPreProcessingFailed` `integer`

Counter for UDP packets failing preprocessing.

Default value:

[source,json]
----
0
----

===== `UDPRejected` `integer`

Counter for UDP packets dropped due to policy.

Default value:

[source,json]
----
0
----

===== `UDPSynAckDropBadClaims` `integer`

Counter for UDP SYN ACK packets dropped due to bad claims.

Default value:

[source,json]
----
0
----

===== `UDPSynAckMissingClaims` `integer`

Counter for UDP SYN ACK packets dropped due to missing claims.

Default value:

[source,json]
----
0
----

===== `UDPSynAckPolicy` `integer`

Counter for UDP SYN ACK packets dropped due to bad claims.

Default value:

[source,json]
----
0
----

===== `UDPSynDrop` `integer`

Counter for dropped UDP SYN transmits.

Default value:

[source,json]
----
0
----

===== `UDPSynDropPolicy` `integer`

Counter for dropped UDP SYN policy.

Default value:

[source,json]
----
0
----

===== `UDPSynInvalidToken` `integer`

Counter for dropped UDP FIN handshake packets.

Default value:

[source,json]
----
0
----

===== `UDPSynMissingClaims` `integer`

Counter for UDP SYN packet dropped due to missing claims.

Default value:

[source,json]
----
0
----

===== `UnknownError` `integer`

Counter for unknown error.

Default value:

[source,json]
----
0
----

===== `connectionsAnalyzed` `integer`

Non-zero counter indicates analyzed connections for unencrypted,
encrypted, and packets from endpoint applications with the TCP Fast Open
option set. These are not dropped counter.

Default value:

[source,json]
----
0
----

===== `connectionsDropped` `integer`

Non-zero counter indicates dropped connections because of invalid state,
non-processing unit traffic, or out of order packets.

Default value:

[source,json]
----
0
----

===== `connectionsExpired` `integer`

Non-zero counter indicates expired connections because of response not
being received within a certain amount of time after the request is
made.

Default value:

[source,json]
----
0
----

===== `droppedPackets` `integer`

Non-zero counter indicates dropped packets that did not hit any of our
iptables rules and queue drops.

Default value:

[source,json]
----
0
----

===== `encryptionFailures` `integer`

Non-zero counter indicates encryption processing failures of data
packets.

Default value:

[source,json]
----
0
----

===== `enforcerID` `string` [`required`]

Identifier of the enforcer sending the report.

===== `enforcerNamespace` `string` [`required`]

Namespace of the enforcer sending the report.

===== `externalNetworkConnections` `integer`

Non-zero counter indicates connections going to and from external
networks. These may be drops or allowed counters.

Default value:

[source,json]
----
0
----

===== `policyDrops` `integer`

Non-zero counter indicates packets dropped due to a reject policy.

Default value:

[source,json]
----
0
----

===== `processingUnitID` `string`

PUID is the ID of the processing unit reporting the counter.

===== `processingUnitNamespace` `string`

Namespace of the processing unit reporting the counter.

===== `timestamp` `time`

Timestamp is the date of the report.

===== `tokenDrops` `integer`

Non-zero counter indicates packets rejected due to anything related to
token creation/parsing failures.

Default value:

[source,json]
----
0
----

=== Enforcer

Contains all parameters associated with a registered enforcer. The
object is mainly maintained by the enforcers themselves. Users can read
the object in order to understand the current status of the enforcers.

==== Example

[source,json]
----
{
  "FQDN": "server1.domain.com",
  "certificateRequest": "-----BEGIN CERTIFICATE REQUEST-----
MIICvDCCAaQCAQAwdzELMAkGA1UEBhMCVVMxDTALBgNVBAgMBFV0YWgxDzANBgNV
BAcMBkxpbmRvbjEWMBQGA1UECgwNRGlnaUNlcnQgSW5jLjERMA8GA1UECwwIRGln
aUNlcnQxHTAbBgNVBAMMFGV4YW1wbGUuZGlnaWNlcnQuY29tMIIBIjANBgkqhkiG
9w0BAQEFAAOCAQ8AMIIBCgKCAQEA8+To7d+2kPWeBv/orU3LVbJwDrSQbeKamCmo
wp5bqDxIwV20zqRb7APUOKYoVEFFOEQs6T6gImnIolhbiH6m4zgZ/CPvWBOkZc+c
1Po2EmvBz+AD5sBdT5kzGQA6NbWyZGldxRthNLOs1efOhdnWFuhI162qmcflgpiI
WDuwq4C9f+YkeJhNn9dF5+owm8cOQmDrV8NNdiTqin8q3qYAHHJRW28glJUCZkTZ
wIaSR6crBQ8TbYNE0dc+Caa3DOIkz1EOsHWzTx+n0zKfqcbgXi4DJx+C1bjptYPR
BPZL8DAeWuA8ebudVT44yEp82G96/Ggcf7F33xMxe0yc+Xa6owIDAQABoAAwDQYJ
KoZIhvcNAQEFBQADggEBAB0kcrFccSmFDmxox0Ne01UIqSsDqHgL+XmHTXJwre6D
hJSZwbvEtOK0G3+dr4Fs11WuUNt5qcLsx5a8uk4G6AKHMzuhLsJ7XZjgmQXGECpY
Q4mC3yT3ZoCGpIXbw+iP3lmEEXgaQL0Tx5LFl/okKbKYwIqNiyKWOMj7ZR/wxWg/
ZDGRs55xuoeLDJ/ZRFf9bI+IaCUd1YrfYcHIl3G87Av+r49YVwqRDT0VDV7uLgqn
29XI1PpVUNCPQGn9p/eX6Qo7vpDaPybRtA2R7XLKjQaF9oXWeCUqy1hvJac9QFO2
97Ob1alpHPoZ7mWiEuJwjBPii6a9M9G30nUo39lBi1w=
-----END CERTIFICATE REQUEST-----",
  "collectInfo": false,
  "enforcementStatus": "Inactive",
  "lastCollectionID": "xxx-xxx-xxx-xxx -",
  "logLevel": "Info",
  "logLevelDuration": "10s",
  "machineID": "3F23E8DF-C56D-45CF-89B8-A867F3956409",
  "name": "the name",
  "operationalStatus": "Registered",
  "protected": false,
  "updateAvailable": false
}
----

==== Relations

===== `GET /enforcers`

Retrieves the list of enforcers.

Parameters:

* `q` (`string`): Filtering query. Consequent `q` parameters will form
an or.

===== `POST /enforcers`

Creates a new enforcer.

===== `DELETE /enforcers/:id`

Deletes the enforcer with the given ID.

Parameters:

* `q` (`string`): Filtering query. Consequent `q` parameters will form
an or.

===== `GET /enforcers/:id`

Retrieves the enforcer with the given ID.

===== `PUT /enforcers/:id`

Updates the enforcer with the given ID.

===== `GET /auditprofilemappingpolicies/:id/enforcers`

Returns the list of enforcers that are affected by this mapping.

===== `GET /enforcerprofilemappingpolicies/:id/enforcers`

Returns the list of enforcers affected by an enforcer profile mapping.

===== `GET /hostservicemappingpolicies/:id/enforcers`

Returns the list of enforcers that are affected by this mapping.

===== `GET /enforcers/:id/auditprofiles`

Returns a list of the audit profiles that must be applied to this
enforcer.

===== `GET /enforcers/:id/debugbundles`

Retrieves the list of debug bundles.

===== `POST /enforcers/:id/debugbundles`

Uploads a debug bundle.

===== `GET /enforcers/:id/enforcerprofiles`

Returns the enforcer profile that must be used by an enforcer.

===== `POST /enforcers/:id/enforcerrefreshes`

Sends a Enforcer Refresh command.

===== `GET /enforcers/:id/hostservices`

Returns a list of the host services policies that apply to this
enforcer.

Parameters:

* `appliedServices` (`boolean`): Valid when retrieved for a given
enforcer and returns the applied services.
* `setServices` (`boolean`): Instructs the backend to cache the services
that were resolved. services.

===== `GET /enforcers/:id/poke`

Sends a poke empty object. This is used to ensure an enforcer is up and
running.

Parameters:

* `cpuload` (`float`): Deprecated.
* `enforcementStatus` (`enum(Failed | Inactive | Active)`): If set,
changes the enforcement status of the enforcer alongside with the poke.
* `forceFullPoke` (`boolean`): If set, it will trigger a full poke
(slower).
* `memory` (`integer`): Deprecated.
* `processes` (`integer`): Deprecated.
* `sessionClose` (`boolean`): If set, terminates a session for an
enforcer.
* `sessionID` (`string`): If set, sends the current session ID of an
enforcer.
* `status` (`enum(Registered | Connected | Disconnected)`): If set,
changes the status of the enforcer alongside with the poke.
* `ts` (`time`): time of report. If not set, local server time will be
used.
* `version` (`string`): If set, version of the current running enforcer.
* `zhash` (`integer`): Can be set to help backend target the correct
shard where the enforcer is stored.

===== `GET /enforcers/:id/trustedcas`

Returns the list of certificate authorities that should be trusted by
this enforcer.

Parameters:

* `type` (`enum(Any | X509 | SSH)`): Type of certificate to get.

==== Attributes

===== `FQDN` `string` [`required`,`creation_only`]

Contains the fully qualified domain name (FQDN) of the server where the
enforcer is running.

===== `ID` `string` [`identifier`,`autogenerated`,`read_only`]

Identifier of the object.

===== `annotations` `map[string][]string`

Stores additional information about an entity.

===== `associatedTags` `[]string`

List of tags attached to an entity.

===== `certificate` `string` [`autogenerated`,`read_only`]

The certificate of the enforcer.

===== `certificateRequest` `string`

If not empty during a create or update operation, the provided
certificate signing request (CSR) will be validated and signed by the
control plane, providing a renewed certificate.

===== `collectInfo` `boolean`

Indicates to the enforcer whether or not it needs to collect
information.

===== `collectedInfo` `map[string]string`

_This attribute is deprecated_.

Represents the latest information collected by the enforcer.

===== `controller` `string` [`autogenerated`,`read_only`]

The control plane identifier managing this object. This property is
mostly useful when federating multiple control planes.

===== `createTime` `time` [`autogenerated`,`read_only`]

Creation date of the object.

===== `currentVersion` `string`

The version number of the installed enforcer binary.

===== `description` `string` [`max_length=1024`]

Description of the object.

===== `enforcementStatus` `enum(Inactive | Active | Failed)`

Status of the enforcement for host services.

Default value:

[source,json]
----
"Inactive"
----

===== `lastCollectionID` `string`

Identifies the last collection.

===== `lastCollectionTime` `time`

Identifies when the information was collected.

===== `lastSyncTime` `time`

The time and date of the last heartbeat.

===== `localCA` `string` [`autogenerated`]

Contains the initial chain of trust for the enforcer. This value is only
given when you retrieve a single enforcer.

===== `logLevel` `enum(Info | Debug | Warn | Error | Trace)`

Log level of the enforcer.

Default value:

[source,json]
----
"Info"
----

===== `logLevelDuration` `string`

Determines the duration of which the log level will be active, using
https://golang.org/pkg/time/#example_Duration[Golang duration syntax].

Default value:

[source,json]
----
"10s"
----

===== `machineID` `string`

A unique identifier for every machine as detected by the enforcer. It is
based on hardware information such as the SMBIOS UUID, MAC addresses of
interfaces, or cloud provider IDs.

===== `metadata` `[]string` [`creation_only`]

Contains tags that can only be set during creation, must all start with
the `@' prefix, and should only be used by external systems.

===== `name` `string` [`required`,`max_length=256`]

Name of the entity.

===== `namespace` `string` [`autogenerated`,`read_only`]

Namespace tag attached to an entity.

===== `normalizedTags` `[]string` [`autogenerated`,`read_only`]

Contains the list of normalized tags of the entities.

===== `operationalStatus` `enum(Registered | Connected | Disconnected | Initialized)`

The status of the enforcer.

Default value:

[source,json]
----
"Registered"
----

===== `protected` `boolean`

Defines if the object is protected.

===== `publicToken` `string` [`autogenerated`,`read_only`]

The public token of the server that will be included in the datapath and
is signed by the private certificate authority.

===== `startTime` `time`

The time and date on which this enforcer was started. The enforcer
reports this and the value is preserved across disconnects.

===== `subnets` `[]string`

Local subnets of this enforcer.

===== `unreachable` `boolean` [`autogenerated`,`read_only`]

The Aporeto control plane sets this value to `true` if it hasn’t heard
from the enforcer in the last five minutes.

===== `updateAvailable` `boolean`

If `true`, the enforcer version is outdated and should be updated.

===== `updateTime` `time` [`autogenerated`,`read_only`]

Last update date of the object.

=== EnforcerLog

An enforcer log represents the log collected by an enforcer. Each
enforcer log can have partial or complete data. The collectionID is used
to aggregate the multipart data into one.

==== Example

[source,json]
----
{
  "collectionID": "xxx-xxx-xxx-xxx",
  "enforcerID": "xxx-xxx-xxx-xxx",
  "protected": false
}
----

==== Relations

===== `GET /enforcerlog`

Retrieves the list of enforcerlogs.

Parameters:

* `q` (`string`): Filtering query. Consequent `q` parameters will form
an or.

===== `POST /enforcerlog`

Creates a new enforcerlog.

===== `GET /enforcerlog/:id`

Retrieves the enforcerlog with the given ID.

==== Attributes

===== `ID` `string` [`identifier`,`autogenerated`,`read_only`]

Identifier of the object.

===== `annotations` `map[string][]string`

Stores additional information about an entity.

===== `associatedTags` `[]string`

List of tags attached to an entity.

===== `collectionID` `string` [`required`]

CollectionID is the ID of the enforcer log. CollectionID is used to
aggregate the multipart data.

===== `createTime` `time` [`autogenerated`,`read_only`]

Creation date of the object.

===== `data` `string`

Represents the data collected by the enforcer.

===== `enforcerID` `string` [`required`]

ID of the enforcer.

===== `namespace` `string` [`autogenerated`,`read_only`]

Namespace tag attached to an entity.

===== `normalizedTags` `[]string` [`autogenerated`,`read_only`]

Contains the list of normalized tags of the entities.

===== `page` `integer`

Number assigned to each log in the increasing order.

===== `protected` `boolean`

Defines if the object is protected.

===== `title` `string`

Title of the log.

===== `updateTime` `time` [`autogenerated`,`read_only`]

Last update date of the object.

=== EnforcerReport

Post a new enforcer statistics report.

==== Example

[source,json]
----
{
  "CPULoad": 10,
  "ID": "xxx-xxx-xxx-xxx",
  "memory": 10000,
  "name": "aporeto-enforcerd-xxx",
  "namespace": "/my/ns",
  "processes": 10,
  "timestamp": "2018-06-14T23:10:46.420397985Z"
}
----

==== Relations

===== `POST /enforcerreports`

Create a enforcer statistics report.

==== Attributes

===== `CPULoad` `float`

Total CPU utilization of the enforcer as a percentage of vCPUs.

===== `ID` `string` [`required`]

ID of the enforcer.

===== `memory` `integer`

Total resident memory used by the enforcer in bytes.

===== `name` `string` [`required`]

Name of the enforcer.

===== `namespace` `string` [`required`]

Namespace of the enforcer.

===== `processes` `integer`

Number of active processes of the enforcer.

===== `timestamp` `time` [`required`]

Date of the report.

=== EnforcerTraceReport

Post a new enforcer trace that determines how packets are.

==== Example

[source,json]
----
{
  "enforcerID": "5c6cce207ddf1fc159a104bf",
  "enforcerNamespace": "/acme/prod",
  "namespace": "/acme/prod/database",
  "puID": "5c6ccd947ddf1fc159a104b7"
}
----

==== Relations

===== `POST /enforcertracereports`

Create an enforcer trace report.

==== Attributes

===== `enforcerID` `string` [`required`]

ID of the enforcer where the trace was collected.

===== `enforcerNamespace` `string` [`required`]

Namespace of the enforcer where the trace was collected.

===== `namespace` `string` [`required`]

Namespace of the processing unit where the trace was collected.

===== `puID` `string` [`required`]

ID of the processing unit where the trace was collected.

=== PacketReport

Post a new packet tracing report.

==== Example

[source,json]
----
{
  "destinationPort": 11000,
  "encrypt": false,
  "enforcerID": "xxxx-xxx-xxxx",
  "enforcerNamespace": "/my/namespace",
  "event": "Rcv",
  "mark": 123123,
  "namespace": "/my/namespace",
  "packetID": 12333,
  "protocol": 6,
  "puID": "xxx-xxx-xxx",
  "rawPacket": "abcd",
  "sourcePort": 80,
  "timestamp": "2018-06-14T23:10:46.420397985Z",
  "triremePacket": true
}
----

==== Relations

===== `POST /packetreports`

Create a packet trace report.

==== Attributes

===== `TCPFlags` `integer`

Flags are the TCP flags of the packet.

===== `claims` `[]string`

Claims is the list of claims detected for the packet.

===== `destinationIP` `string`

The destination IP address of the packet.

===== `destinationPort` `integer` [`max_value=65536.000000`]

The destination port of a TCP or UDP packet.

===== `dropReason` `string`

If `event` is set to `Dropped`, contains the reason that the packet was
dropped. Otherwise empty.

===== `encrypt` `boolean`

Set to `true` if the packet was encrypted.

===== `enforcerID` `string` [`required`]

Identifier of the enforcer sending the report.

===== `enforcerNamespace` `string` [`required`]

Namespace of the enforcer sending the report.

===== `event` `enum(Received | Transmitted | Dropped)` [`required`]

The event that triggered the report.

===== `mark` `integer`

Mark is the mark value of the packet.

===== `namespace` `string` [`required`]

Namespace of the processing unit reporting the packet.

===== `packetID` `integer`

The ID of the IP header of the reported packet.

===== `protocol` `integer` [`max_value=255.000000`]

Protocol number.

===== `puID` `string`

The ID of the processing unit reporting the packet.

===== `rawPacket` `string`

The first 64 bytes of the packet.

Default value:

[source,json]
----
"abcd"
----

===== `sourceIP` `string`

The source IP address of the packet.

===== `sourcePort` `integer` [`max_value=65536.000000`]

The source port of the packet.

===== `timestamp` `time` [`required`]

The time-date stamp of the report.

===== `triremePacket` `boolean`

Set to `true` if the packet arrived with the Trireme options (default).

Default value:

[source,json]
----
true
----

=== PingPair

Represents a pair of ping probes.

==== Attributes

===== `request` link:#pingprobe[`pingprobe`]

Contains the request probe information.

===== `response` link:#pingprobe[`pingprobe`]

Contains the response probe information.

=== PingProbe

Represents the result of a unique ping probe. They are aggregated into a
PingResult.

==== Example

[source,json]
----
{
  "applicationListening": false,
  "claimsType": "Transmitted",
  "enforcerID": "xxx-xxx-xxx-xxx",
  "enforcerNamespace": "/my/ns",
  "excludedNetworks": false,
  "isServer": false,
  "pingID": "xxx-xxx-xxx-xxx",
  "remoteEndpointType": "ProcessingUnit",
  "remoteNamespaceType": "Plain",
  "targetTCPNetworks": false,
  "type": "Request"
}
----

==== Relations

===== `GET /pingprobes/:id`

Retrieves a ping result.

===== `POST /processingunits/:id/pingprobes`

Create a ping probe.

==== Attributes

===== `ACLPolicyAction` `string`

Action of the ACL policy.

===== `ACLPolicyID` `string`

ID of the ACL policy.

===== `ID` `string` [`identifier`,`autogenerated`,`read_only`]

Identifier of the object.

===== `RTT` `string`

Time taken for a single request-response to complete.

===== `applicationListening` `boolean`

If true, application responded to the request.

===== `claims` `[]string`

Claims of the processing unit.

===== `claimsType` `enum(Transmitted | Received)`

Type of claims reported.

===== `createTime` `time` [`autogenerated`,`read_only`]

Creation date of the object.

===== `enforcerID` `string` [`required`]

ID of the enforcer.

===== `enforcerNamespace` `string` [`required`]

Namespace of the enforcer.

===== `enforcerVersion` `string`

Semantic version of the enforcer.

===== `error` `string`

A non-empty error indicates a failure.

===== `excludedNetworks` `boolean`

If true, destination IP is in `excludedNetworks`.

===== `fourTuple` `string`

Four tuple in the format sip:dip:spt:dpt.

===== `isServer` `boolean`

If true, the report was generated by the server.

===== `iterationIndex` `integer`

Holds the iteration number this probe is attached to.

===== `namespace` `string` [`autogenerated`,`read_only`]

Namespace tag attached to an entity.

===== `payloadSize` `integer`

Size of the payload attached to the packet.

===== `peerCertExpiry` `string`

Represents the expiry of the peer certificate.

===== `peerCertIssuer` `string`

Represents the issuer of the peer certificate.

===== `peerCertSubject` `string`

Represents the subject of the peer certificate.

===== `pingID` `string` [`required`]

PingID unique to a single ping control.

===== `policyAction` `string`

Action of the policy.

===== `policyID` `string`

ID of the policy.

===== `policyNamespace` `string`

ID of the policy.

===== `processingUnitID` `string`

ID of the reporting processing unit.

===== `protocol` `integer`

Protocol used for the communication.

===== `remoteController` `string`

Controller of the remote endpoint.

===== `remoteEndpointType` `enum(ProcessingUnit | External)`

Represents the remote endpoint type.

===== `remoteNamespace` `string`

Namespace of the remote processing unit.

===== `remoteNamespaceType` `enum(Plain | Hash)`

Type of the namespace reported.

===== `remoteProcessingUnitID` `string`

ID of the remote processing unit.

===== `seqNum` `integer`

Sequence number of the TCP packet. number.

===== `serviceID` `string`

ID of the service If the service type is a proxy.

===== `serviceType` `string` [`autogenerated`,`read_only`]

Type of the service.

===== `targetTCPNetworks` `boolean`

If true, destination IP is in `targetTCPNetworks`.

===== `type` `enum(Request | Response)`

Type of the report.

===== `updateTime` `time` [`autogenerated`,`read_only`]

Last update date of the object.

=== PingRequest

Initiates a ping request for enforcer debugging.

==== Example

[source,json]
----
{
  "iterations": 1,
  "refreshID": "xxxx-xxxx-xxxx"
}
----

==== Relations

===== `POST /pingrequests`

Initiate a new the ping request.

==== Attributes

===== `iterations` `integer` [`min_value=1.000000`,`max_value=20.000000`]

Number of probes that will be triggered.

Default value:

[source,json]
----
1
----

===== `pingID` `string` [`autogenerated`,`read_only`]

Unique ID generated for each ping request.

===== `refreshID` `string` [`required`]

Contains the refresh ID set by processing unit refresh event.

=== PingResult

Represents the results of a ping request.

==== Relations

===== `GET /pingresults`

Retrieves a ping result.

Parameters:

* `q` (`string`): Filtering query. Consequent `q` parameters will form
an or.

==== Attributes

===== `ID` `string` [`identifier`,`autogenerated`,`read_only`]

Identifier of the object.

===== `createTime` `time` [`autogenerated`,`read_only`]

Creation date of the object.

===== `errors` `[]string` [`autogenerated`,`read_only`]

May contain a list of errors that have happened during the collection.

===== `namespace` `string` [`autogenerated`,`read_only`]

Namespace tag attached to an entity.

===== `pingID` `string` [`autogenerated`,`read_only`]

Contains the Ping ID.

===== `pingPairs` link:#pingpair[`[]pingpair`]

Contains the result of aggregated ping pairs.

===== `refreshID` `string` [`autogenerated`,`read_only`]

Contains the refresh ID set by processing unit refresh event.

===== `remoteProbes` link:#remotepingprobe[`[]remotepingprobe`]

Contains information about missing probes in the result. This field will
be populated in the ping probe is managed by a remote controller
(federation) or is stored in a namespace you don’t have any permissions
on.

===== `updateTime` `time` [`autogenerated`,`read_only`]

Last update date of the object.

=== RemotePingProbe

Represents information about a remote ping probe that is governed by a
different set of permissions.

==== Attributes

===== `controllerID` `string` [`autogenerated`,`read_only`]

The controller ID that manages the ping report.

===== `namespace` `string` [`autogenerated`,`read_only`]

The namespace where the ping report is stored. Only applicable when the
remote controller is empty.

===== `namespaceType` `enum(Plain | Hash)` [`autogenerated`,`read_only`]

Type of the namespace reported. It can be hash or plain, depending on
various factors.

===== `probeID` `string` [`autogenerated`,`read_only`]

The ID of the probe. Only applicable when the remote controller is
empty.

=== TraceMode

Represents the tracing mode to apply to a processing unit.

==== Example

[source,json]
----
{
  "IPTables": false,
  "applicationConnections": false,
  "interval": "10s",
  "networkConnections": false
}
----

==== Attributes

===== `IPTables` `boolean`

Instructs the enforcers to provide an iptables trace for a processing
unit.

===== `applicationConnections` `boolean`

Instructs the enforcer to send records for all application-initiated
connections.

===== `interval` `string`

Determines the length of the time interval that the trace must be
enabled, using https://golang.org/pkg/time/#example_Duration[Golang
duration syntax].

Default value:

[source,json]
----
"10s"
----

===== `networkConnections` `boolean`

Instructs the enforcer to send records for all network-initiated
connections.

=== TraceRecord

Represents a single trace record from the enforcer.

==== Example

[source,json]
----
{
  "TTL": 64,
  "chain": "PREROUTING",
  "destinationIP": "10.1.1.30",
  "destinationInterface": "en0",
  "destinationPort": 80,
  "length": 98,
  "packetID": 10,
  "protocol": 80,
  "ruleID": 10,
  "sourceIP": "10.1.1.30",
  "sourceInterface": "en0",
  "sourcePort": 80,
  "tableName": "raw",
  "timestamp": "2018-06-14T23:10:46.420397985Z"
}
----

==== Attributes

===== `TTL` `integer` [`required`,`max_value=255.000000`]

The time to live (TTL) value of the packet.

===== `chain` `string` [`required`]

Chain that the trace was collected from.

===== `destinationIP` `string` [`required`]

The destination IP.

===== `destinationInterface` `string`

The destination interface of the packet.

===== `destinationPort` `integer` [`required`,`min_value=1.000000`,`max_value=65536.000000`]

The destination UPD or TCP port of the packet.

===== `length` `integer` [`required`,`max_value=65536.000000`]

Length of the observed packet.

===== `packetID` `integer` [`required`]

The IP packet header ID.

===== `protocol` `integer` [`required`,`max_value=65536.000000`]

The protocol of the packet.

===== `ruleID` `integer` [`required`]

Priority index of the iptables entry that was hit.

===== `sourceIP` `string` [`required`]

Source IP of the packet.

===== `sourceInterface` `string`

Source interface of the packet.

===== `sourcePort` `integer` [`required`,`min_value=1.000000`,`max_value=65536.000000`]

Source TCP or UDP port of the packet.

===== `tableName` `string` [`required`]

The iptables name that the trace collected.

===== `timestamp` `time` [`required`]

The time-date stamp of the report.
