#!/bin/bash

export BRANCH=master


echo "Getting API overview"
curl --silent -o api-overview.md "https://raw.githubusercontent.com/aporeto-inc/gaia/${BRANCH}/doc/README.md"

pandoc api-overview.md -o api-overview.adoc

cat << EOF > about.adoc

// WE PULL THIS CONTENT FROM https://github.com/aporeto-inc/gaia
// DO NOT EDIT THIS FILE.
// YOU MUST SUBMIT A PR AGAINST THE UPSTREAM REPO.

= About the Segment Console API

$(sed -e '1,2d' < api-overview.adoc)
EOF

rm -f api-overview.md
rm -f api-overview.adoc
rm -f segment_console_api/about.adoc
mv about.adoc segment_console_api/about.adoc



echo "Getting API reference"
curl --silent -o api-ref.md "https://raw.githubusercontent.com/aporeto-inc/gaia/${BRANCH}/doc/documentation.md"

pandoc api-ref.md -o api-ref.adoc

cat << EOF > reference.adoc

// WE PULL THIS CONTENT FROM https://github.com/aporeto-inc/gaia
// DO NOT EDIT THIS FILE.
// YOU MUST SUBMIT A PR AGAINST THE UPSTREAM REPO.

= Segment Console API reference

$(sed -e '1,5d' < api-ref.adoc)


EOF

rm -f api-ref.md
rm -f api-ref.adoc
rm -f segment_console_api/reference.adoc
mv reference.adoc segment_console_api/reference.adoc

