#!/bin/bash
# Must set GITHUB_TOKEN and have access to private apoctl repo in aporeto-inc org
# Requires GNU sed, expects to use gsed
# Requires GNU csplit, expects to call it as gcsplit

export BRANCH=master

echo "Getting concepts"
curl --silent -o concepts.md -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/junon/master/src/content/next/concepts/_index.md"
curl --silent -o enforcer-policy-pcc.png -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/junon/master/src/static/img/diagrams/enforcer-policy-pcc.png"
curl --silent -o authentication-pcc.png -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/junon/master/src/static/img/diagrams/authentication-pcc.png"
curl --silent -o enforcer-tcp-pcc.png -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/junon/master/src/static/img/diagrams/enforcer-tcp-pcc.png"
curl --silent -o pus.png -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/junon/master/src/static/img/diagrams/pus.png"

pandoc concepts.md -o concepts.adoc

gsed -i -e 's/^==/===/g' concepts.adoc
gsed -i -e 's/\/img\/diagrams\///g' concepts.adoc

gsed -i -e '1 i\// WE PULL THIS CONTENT FROM https://github.com/aporeto-inc/junon\n// DO NOT EDIT THIS FILE.\n// YOU MUST SUBMIT A PR AGAINST THE UPSTREAM REPO.\n// THE UPSTREAM REPO IS CURRENTLY PRIVATE.\n\n== Concepts\n' concepts.adoc

rm -f concepts.md
rm -f concepts/concepts.adoc
mv concepts.adoc concepts/concepts.adoc
mv enforcer-tcp-pcc.png concepts/images/enforcer-tcp-pcc.png
mv authentication-pcc.png concepts/images/authentication-pcc.png
mv enforcer-policy-pcc.png concepts/images/enforcer-policy-pcc.png
mv pus.png concepts/images/pus.png

echo "Getting troubleshooting: defender"
curl --silent -o defender.md -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/junon/master/src/content/next/troubleshoot/defender/_index.md"

pandoc defender.md -o defender.adoc

gsed -i -e 's/^==/===/g' defender.adoc

gsed -i -e '1 i\// WE PULL THIS CONTENT FROM https://github.com/aporeto-inc/junon\n// DO NOT EDIT THIS FILE.\n// YOU MUST SUBMIT A PR AGAINST THE UPSTREAM REPO.\n// THE UPSTREAM REPO IS CURRENTLY PRIVATE.\n\n== Defender\n' \
  defender.adoc

rm -f defender.md
rm -f troubleshoot/defender.adoc
mv defender.adoc troubleshoot/defender.adoc

echo "Getting troubleshooting: console"
curl --silent -o console.md -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/junon/master/src/content/next/troubleshoot/segment-console/_index.md"

pandoc console.md -o console.adoc

gsed -i -e 's/^==/===/g' console.adoc

gsed -i -e '1 i\// WE PULL THIS CONTENT FROM https://github.com/aporeto-inc/junon\n// DO NOT EDIT THIS FILE.\n// YOU MUST SUBMIT A PR AGAINST THE UPSTREAM REPO.\n// THE UPSTREAM REPO IS CURRENTLY PRIVATE.\n\n== Defender\n' \
  console.adoc

rm -f console.md
rm -f troubleshoot/console.adoc
mv console.adoc troubleshoot/console.adoc

echo "Getting API overview"
curl --silent -o api-overview.md "https://raw.githubusercontent.com/aporeto-inc/gaia/${BRANCH}/doc/README.md"

pandoc api-overview.md -o api-overview.adoc

cat << EOF > about.adoc

// WE PULL THIS CONTENT FROM https://github.com/aporeto-inc/gaia
// DO NOT EDIT THIS FILE.
// YOU MUST SUBMIT A PR AGAINST THE UPSTREAM REPO.

== About the Segment Console API

$(sed -e '1,2d' < api-overview.adoc)
EOF

rm -f api-overview.md
rm -f api-overview.adoc
rm -f segment_console_api/about.adoc
mv about.adoc segment_console_api/about.adoc


echo "Getting API reference"
curl --silent -o api-ref.md "https://raw.githubusercontent.com/aporeto-inc/gaia/${BRANCH}/doc/documentation.md"
echo "Splitting file"
gcsplit --prefix='api-ref' --suffix-format='%03d.md' api-ref.md '/^##\s/' "{*}"

rm api-ref000.md
echo "Saving core"
pandoc api-ref001.md -o api-core.adoc
mv api-core.adoc segment_console_api/api-core.adoc
rm api-ref001.md
echo "Saving core/account"
pandoc api-ref002.md -o api-core-account.adoc
mv api-core-account.adoc segment_console_api/api-core-account.adoc
rm api-ref002.md
echo "Saving core/authentication"
pandoc api-ref003.md -o api-core-authentication.adoc
mv api-core-authentication.adoc segment_console_api/api-core-authentication.adoc
rm api-ref003.md
echo "Saving core/billing"
pandoc api-ref004.md -o api-core-billing.adoc
mv api-core-billing.adoc segment_console_api/api-core-billing.adoc
rm api-ref004.md
echo "Saving core/enforcer"
pandoc api-ref005.md -o api-core-enforcer.adoc
mv api-core-enforcer.adoc segment_console_api/api-core-enforcer.adoc
rm api-ref005.md
echo "Saving core/monitoring"
pandoc api-ref006.md -o api-core-monitoring.adoc
mv api-core-monitoring.adoc segment_console_api/api-core-monitoring.adoc
rm api-ref006.md
echo "Saving core/namespace"
pandoc api-ref007.md -o api-core-namespace.adoc
mv api-core-namespace.adoc segment_console_api/api-core-namespace.adoc
rm api-ref007.md
echo "Saving core/policy"
pandoc api-ref008.md -o api-core-policy.adoc
mv api-core-policy.adoc segment_console_api/api-core-policy.adoc
rm api-ref008.md
echo "Saving core/processingunit"
pandoc api-ref009.md -o api-core-processingunit.adoc
mv api-core-processingunit.adoc segment_console_api/api-core-processingunit.adoc
rm api-ref009.md
echo "Saving core/tag"
pandoc api-ref010.md -o api-core-tag.adoc
mv api-core-tag.adoc segment_console_api/api-core-tag.adoc
rm api-ref010.md
echo "Saving core/workflow"
pandoc api-ref011.md -o api-core-workflow.adoc
mv api-core-workflow.adoc segment_console_api/api-core-workflow.adoc
rm api-ref011.md
echo "Saving debug"
pandoc api-ref012.md -o api-debug.adoc
mv api-debug.adoc segment_console_api/api-debug.adoc
rm api-ref012.md
echo "Saving ext/documentation"
pandoc api-ref013.md -o api-ext-documentation.adoc
mv api-ext-documentation.adoc segment_console_api/api-ext-documentation.adoc
rm api-ref013.md
echo "Saving integration/apiproxy"
pandoc api-ref014.md -o api-integration-apiproxy.adoc
mv api-integration-apiproxy.adoc segment_console_api/api-integration-apiproxy.adoc
rm api-ref014.md
echo "Saving integration/app"
pandoc api-ref015.md -o api-integration-app.adoc
mv api-integration-app.adoc segment_console_api/api-integration-app.adoc
rm api-ref015.md
echo "Saving integration/automation"
pandoc api-ref016.md -o api-integration-automation.adoc
mv api-integration-automation.adoc segment_console_api/api-integration-automation.adoc
rm api-ref016.md
echo "Saving internal/token"
pandoc api-ref017.md -o api-internal-token.adoc
mv api-internal-token.adoc segment_console_api/api-internal-token.adoc
rm api-ref017.md
echo "Saving internal/x509"
pandoc api-ref018.md -o api-internal-x509.adoc
mv api-internal-x509.adoc segment_console_api/api-internal-x509.adoc
rm api-ref018.md
echo "Saving policy/access"
pandoc api-ref019.md -o api-policy-access.adoc
mv api-policy-access.adoc segment_console_api/api-policy-access.adoc
rm api-ref019.md
echo "Saving policy/audit"
pandoc api-ref020.md -o api-policy-audit.adoc
mv api-policy-audit.adoc segment_console_api/api-policy-audit.adoc
rm api-ref020.md
echo "Saving policy/authorization"
pandoc api-ref021.md -o api-policy-authorization.adoc
mv api-policy-authorization.adoc segment_console_api/api-policy-authorization.adoc
rm api-ref021.md
echo "Saving policy/dns"
pandoc api-ref022.md -o api-policy-dns.adoc
mv api-policy-dns.adoc segment_console_api/api-policy-dns.adoc
rm api-ref022.md
echo "Saving policy/enforcerconfig"
pandoc api-ref023.md -o api-policy-enforcerconfig.adoc
mv api-policy-enforcerconfig.adoc segment_console_api/api-policy-enforcerconfig.adoc
rm api-ref023.md
echo "Saving policy/files"
pandoc api-ref024.md -o api-policy-files.adoc
mv api-policy-files.adoc segment_console_api/api-policy-files.adoc
rm api-ref024.md
echo "Saving policy/hooks"
pandoc api-ref025.md -o api-policy-hooks.adoc
mv api-policy-hooks.adoc segment_console_api/api-policy-hooks.adoc
rm api-ref025.md
echo "Saving policy/hosts"
pandoc api-ref026.md -o api-policy-hosts.adoc
mv api-policy-hosts.adoc segment_console_api/api-policy-hosts.adoc
rm api-ref026.md
echo "Saving policy/networking"
pandoc api-ref027.md -o api-policy-networking.adoc
mv api-policy-networking.adoc segment_console_api/api-policy-networking.adoc
rm api-ref027.md
echo "Saving policy/processingunits"
pandoc api-ref028.md -o api-policy-processingunits.adoc
mv api-policy-processingunits.adoc segment_console_api/api-policy-processingunits.adoc
rm api-ref028.md
echo "Saving policy/quota"
pandoc api-ref029.md -o api-policy-quota.adoc
mv api-policy-quota.adoc segment_console_api/api-policy-quota.adoc
rm api-ref029.md
echo "Saving policy/services"
pandoc api-ref030.md -o api-policy-services.adoc
mv api-policy-services.adoc segment_console_api/api-policy-services.adoc
rm api-ref030.md
echo "Saving policy/ssh"
pandoc api-ref031.md -o api-policy-ssh.adoc
mv api-policy-ssh.adoc segment_console_api/api-policy-ssh.adoc
rm api-ref031.md
echo "Saving policy/token"
pandoc api-ref032.md -o api-policy-token.adoc
mv api-policy-token.adoc segment_console_api/api-policy-token.adoc
rm api-ref032.md
echo "Saving visualization/depmaps"
pandoc api-ref033.md -o api-visualization-depmaps.adoc
mv api-visualization-depmaps.adoc segment_console_api/api-visualization-depmaps.adoc
rm api-ref033.md
echo "Saving visualization/statsquery"
pandoc api-ref034.md -o api-visualization-statsquery.adoc
mv api-visualization-statsquery.adoc segment_console_api/api-visualization-statsquery.adoc
rm api-ref034.md

rm api-ref.md

echo "Getting apoctl usage"
curl --silent -o apoctl-ref.md -H "Authorization: token ${GITHUB_TOKEN}" "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/apoctl.md"

pandoc apoctl-ref.md -o apoctl-ref.adoc

cat << EOF > usage.adoc

// WE PULL THIS CONTENT FROM https://github.com/aporeto-inc/apoctl
// DO NOT EDIT THIS FILE.
// YOU MUST SUBMIT A PR AGAINST THE UPSTREAM REPO.
// THE UPSTREAM REPO IS CURRENTLY PRIVATE.

== Usage

$(sed -e '1,2d' < apoctl-ref.adoc)
EOF

rm -f apoctl-ref.md
rm -f apoctl-ref.adoc
rm -f apoctl/usage.adoc
mv usage.adoc apoctl/usage.adoc

echo "Getting apoctl api command"

curl --silent -o apoctl-api.md -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/api.md"

echo >> apoctl-api.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/api-all.md" >> apoctl-api.md

echo >> apoctl-api.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/api-count.md" >> apoctl-api.md

echo >> apoctl-api.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/api-create.md" >> apoctl-api.md

echo >> apoctl-api.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/api-delete.md" >> apoctl-api.md

echo >> apoctl-api.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/api-delete-many.md" >> apoctl-api.md

echo >> apoctl-api.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/api-describe.md" >> apoctl-api.md

echo >> apoctl-api.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/api-export.md" >> apoctl-api.md

echo >> apoctl-api.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/api-get.md" >> apoctl-api.md

echo >> apoctl-api.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/api-import.md" >> apoctl-api.md

echo >> apoctl-api.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/api-info.md" >> apoctl-api.md

echo >> apoctl-api.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/api-list.md" >> apoctl-api.md

echo >> apoctl-api.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/api-listen.md" >> apoctl-api.md

echo >> apoctl-api.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/api-search.md" >> apoctl-api.md

echo >> apoctl-api.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/api-stub.md" >> apoctl-api.md

echo >> apoctl-api.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/api-update.md" >> apoctl-api.md

echo >> apoctl-api.md

pandoc apoctl-api.md -o apoctl-api.adoc

cat << EOF > api.adoc

// WE PULL THIS CONTENT FROM https://github.com/aporeto-inc/apoctl
// DO NOT EDIT THIS FILE.
// YOU MUST SUBMIT A PR AGAINST THE UPSTREAM REPO.
// THE UPSTREAM REPO IS CURRENTLY PRIVATE.

$(< apoctl-api.adoc)

EOF

rm -f apoctl-api.md
rm -f apoctl-api.adoc
rm -f apoctl/api.adoc
mv api.adoc apoctl/api.adoc

echo "Getting apoctl appcred command"

curl --silent -o apoctl-appcred.md -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/appcred.md"

echo >> apoctl-appcred.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/appcred-create.md" >> apoctl-appcred.md

echo >> apoctl-appcred.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/appcred-delete.md" >> apoctl-appcred.md

echo >> apoctl-appcred.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/appcred-disable.md" >> apoctl-appcred.md

echo >> apoctl-appcred.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/appcred-enable.md" >> apoctl-appcred.md

echo >> apoctl-appcred.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/appcred-list.md" >> apoctl-appcred.md

echo >> apoctl-appcred.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/appcred-renew.md" >> apoctl-appcred.md

echo >> apoctl-appcred.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/appcred-roles.md" >> apoctl-appcred.md

echo >> apoctl-appcred.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/appcred-subnets.md" >> apoctl-appcred.md

echo >> apoctl-appcred.md

pandoc apoctl-appcred.md -o apoctl-appcred.adoc

cat << EOF > appcred.adoc

// WE PULL THIS CONTENT FROM https://github.com/aporeto-inc/apoctl
// DO NOT EDIT THIS FILE.
// YOU MUST SUBMIT A PR AGAINST THE UPSTREAM REPO.
// THE UPSTREAM REPO IS CURRENTLY PRIVATE.

$(< apoctl-appcred.adoc)

EOF

rm -f apoctl-appcred.md
rm -f apoctl-appcred.adoc
rm -f apoctl/appcred.adoc
mv appcred.adoc apoctl/appcred.adoc

echo "Getting apoctl auth command"

curl --silent -o apoctl-auth.md -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/auth.md"

echo >> apoctl-auth.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/auth-aporeto.md" >> apoctl-auth.md

echo >> apoctl-auth.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/auth-appcred.md" >> apoctl-auth.md

echo >> apoctl-auth.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/auth-awssts.md" >> apoctl-auth.md

echo >> apoctl-auth.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/auth-azure.md" >> apoctl-auth.md

echo >> apoctl-auth.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/auth-cert.md" >> apoctl-auth.md

echo >> apoctl-auth.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/auth-gcp.md" >> apoctl-auth.md

echo >> apoctl-auth.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/auth-google.md" >> apoctl-auth.md

echo >> apoctl-auth.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/auth-ldap.md" >> apoctl-auth.md

echo >> apoctl-auth.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/auth-oidc.md" >> apoctl-auth.md

echo >> apoctl-auth.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/auth-pcc.md" >> apoctl-auth.md

echo >> apoctl-auth.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/auth-pcc-token.md" >> apoctl-auth.md

echo >> apoctl-auth.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/auth-saml.md" >> apoctl-auth.md

echo >> apoctl-auth.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/auth-token.md" >> apoctl-auth.md

echo >> apoctl-auth.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/auth-verify.md" >> apoctl-auth.md

echo >> apoctl-auth.md

pandoc apoctl-auth.md -o apoctl-auth.adoc

cat << EOF > auth.adoc

// WE PULL THIS CONTENT FROM https://github.com/aporeto-inc/apoctl
// DO NOT EDIT THIS FILE.
// YOU MUST SUBMIT A PR AGAINST THE UPSTREAM REPO.
// THE UPSTREAM REPO IS CURRENTLY PRIVATE.

$(< apoctl-auth.adoc)

EOF

rm -f apoctl-auth.md
rm -f apoctl-auth.adoc
rm -f apoctl-auth.adoc
mv auth.adoc apoctl/auth.adoc


echo "Getting apoctl defender command"

curl --silent -o apoctl-defender.md -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/enforcer.md"

echo >> apoctl-defender.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/enforcer-collect.md" >> apoctl-defender.md

echo >> apoctl-defender.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/enforcer-collect-coredump.md" >> apoctl-defender.md

echo >> apoctl-defender.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/enforcer-collect-counters.md" >> apoctl-defender.md

echo >> apoctl-defender.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/enforcer-collect-logs.md" >> apoctl-defender.md

echo >> apoctl-defender.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/enforcer-collect-packets.md" >> apoctl-defender.md

echo >> apoctl-defender.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/enforcer-collect-pcap.md" >> apoctl-defender.md

echo >> apoctl-defender.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/enforcer-collect-pustate.md" >> apoctl-defender.md

echo >> apoctl-defender.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/enforcer-download.md" >> apoctl-defender.md

echo >> apoctl-defender.md

pandoc apoctl-defender.md -o apoctl-defender.adoc

cat << EOF > defender.adoc

// WE PULL THIS CONTENT FROM https://github.com/aporeto-inc/apoctl
// DO NOT EDIT THIS FILE.
// YOU MUST SUBMIT A PR AGAINST THE UPSTREAM REPO.
// THE UPSTREAM REPO IS CURRENTLY PRIVATE.

$(< apoctl-defender.adoc)

EOF

rm -f apoctl-defender.md
rm -f apoctl-defender.adoc
rm -f apoctl-defender.adoc
mv defender.adoc apoctl/defender.adoc


echo "Getting apoctl stats command"

curl --silent -o apoctl-stats.md -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/stats.md"

echo >> apoctl-stats.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/stats-info.md" >> apoctl-stats.md

echo >> apoctl-stats.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/stats-query.md" >> apoctl-stats.md

echo >> apoctl-stats.md

pandoc apoctl-stats.md -o apoctl-stats.adoc

cat << EOF > stats.adoc

// WE PULL THIS CONTENT FROM https://github.com/aporeto-inc/apoctl
// DO NOT EDIT THIS FILE.
// YOU MUST SUBMIT A PR AGAINST THE UPSTREAM REPO.
// THE UPSTREAM REPO IS CURRENTLY PRIVATE.

$(< apoctl-stats.adoc)

EOF

rm -f apoctl-stats.md
rm -f apoctl-stats.adoc
rm -f apoctl-stats.adoc
mv stats.adoc apoctl/stats.adoc

echo "Getting apoctl reports command"

curl --silent -o apoctl-reports.md -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/reports.md"

echo >> apoctl-reports.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/compliance.md" >> apoctl-reports.md

echo >> apoctl-reports.md

pandoc apoctl-reports.md -o apoctl-reports.adoc

cat << EOF > reports.adoc

// WE PULL THIS CONTENT FROM https://github.com/aporeto-inc/apoctl
// DO NOT EDIT THIS FILE.
// YOU MUST SUBMIT A PR AGAINST THE UPSTREAM REPO.
// THE UPSTREAM REPO IS CURRENTLY PRIVATE.

$(< apoctl-reports.adoc)

EOF

rm -f apoctl-reports.md
rm -f apoctl-reports.adoc
rm -f apoctl-reports.adoc
mv reports.adoc apoctl/reports.adoc
