#!/bin/bash
# Must set GITHUB_TOKEN and have access to private apoctl repo in aporeto-inc org
# Requires GNU sed

export BRANCH=master


echo "Getting API overview"
curl --silent -o api-overview.md "https://raw.githubusercontent.com/aporeto-inc/gaia/${BRANCH}/doc/README.md"

pandoc api-overview.md -o api-overview.adoc

cat << EOF > about.adoc

// WE PULL THIS CONTENT FROM https://github.com/aporeto-inc/gaia
// DO NOT EDIT THIS FILE.
// YOU MUST SUBMIT A PR AGAINST THE UPSTREAM REPO.

== About the Segment Console API

$(sed -e '1,2d' < api-overview.adoc)
EOF

rm -f api-overview.md
rm -f api-overview.adoc
rm -f segment_console_api/about.adoc
mv about.adoc segment_console_api/about.adoc



echo "Getting API reference"
curl --silent -o api-ref.md "https://raw.githubusercontent.com/aporeto-inc/gaia/${BRANCH}/doc/documentation.md"

pandoc api-ref.md -o api-ref.adoc

cat << EOF > reference.adoc

// WE PULL THIS CONTENT FROM https://github.com/aporeto-inc/gaia
// DO NOT EDIT THIS FILE.
// YOU MUST SUBMIT A PR AGAINST THE UPSTREAM REPO.

== Segment Console API reference

$(sed -e '1,5d' < api-ref.adoc)


EOF

rm -f api-ref.md
rm -f api-ref.adoc
rm -f segment_console_api/reference.adoc
mv reference.adoc segment_console_api/reference.adoc

echo "Getting apoctl usage"
curl --silent -o apoctl-ref.md -H "Authorization: token ${GITHUB_TOKEN}" "https://raw.githubusercontent.com/aporeto-inc/apoctl/${BRANCH}/docs/apoctl.md"

pandoc apoctl-ref.md -o apoctl-ref.adoc

cat << EOF > usage.adoc

// WE PULL THIS CONTENT FROM https://github.com/aporeto-inc/apoctl
// DO NOT EDIT THIS FILE.
// YOU MUST SUBMIT A PR AGAINST THE UPSTREAM REPO.
// THE UPSTREAM REPO IS CURRENTLY PRIVATE.

== Usage

$(sed -e '1,2d' < apoctl-ref.adoc)
EOF

rm -f apoctl-ref.md
rm -f apoctl-ref.adoc
rm -f apoctl/usage.adoc
mv usage.adoc apoctl/usage.adoc

echo "Getting apoctl api command"

curl --silent -o apoctl-api.md -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/terms/docs/api.md"

echo >> apoctl-api.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/terms/docs/api-all.md" >> apoctl-api.md

echo >> apoctl-api.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/terms/docs/api-count.md" >> apoctl-api.md

echo >> apoctl-api.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/terms/docs/api-create.md" >> apoctl-api.md

echo >> apoctl-api.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/terms/docs/api-delete.md" >> apoctl-api.md

echo >> apoctl-api.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/terms/docs/api-delete-many.md" >> apoctl-api.md

echo >> apoctl-api.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/terms/docs/api-describe.md" >> apoctl-api.md

echo >> apoctl-api.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/terms/docs/api-export.md" >> apoctl-api.md

echo >> apoctl-api.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/terms/docs/api-get.md" >> apoctl-api.md

echo >> apoctl-api.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/terms/docs/api-import.md" >> apoctl-api.md

echo >> apoctl-api.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/terms/docs/api-info.md" >> apoctl-api.md

echo >> apoctl-api.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/terms/docs/api-list.md" >> apoctl-api.md

echo >> apoctl-api.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/terms/docs/api-listen.md" >> apoctl-api.md

echo >> apoctl-api.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/terms/docs/api-search.md" >> apoctl-api.md

echo >> apoctl-api.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/terms/docs/api-stub.md" >> apoctl-api.md

echo >> apoctl-api.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/terms/docs/api-update.md" >> apoctl-api.md

echo >> apoctl-api.md

pandoc apoctl-api.md -o apoctl-api.adoc

cat << EOF > api.adoc

// WE PULL THIS CONTENT FROM https://github.com/aporeto-inc/apoctl
// DO NOT EDIT THIS FILE.
// YOU MUST SUBMIT A PR AGAINST THE UPSTREAM REPO.
// THE UPSTREAM REPO IS CURRENTLY PRIVATE.

$(< apoctl-api.adoc)

EOF

rm -f apoctl-api.md
rm -f apoctl-api.adoc
rm -f apoctl/api.adoc
mv api.adoc apoctl/api.adoc

echo "Getting apoctl appcred command"

curl --silent -o apoctl-appcred.md -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/terms/docs/appcred.md"

echo >> apoctl-appcred.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/terms/docs/appcred-create.md" >> apoctl-appcred.md

echo >> apoctl-appcred.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/terms/docs/appcred-delete.md" >> apoctl-appcred.md

echo >> apoctl-appcred.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/terms/docs/appcred-disable.md" >> apoctl-appcred.md

echo >> apoctl-appcred.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/terms/docs/appcred-enable.md" >> apoctl-appcred.md

echo >> apoctl-appcred.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/terms/docs/appcred-list.md" >> apoctl-appcred.md

echo >> apoctl-appcred.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/terms/docs/appcred-renew.md" >> apoctl-appcred.md

echo >> apoctl-appcred.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/terms/docs/appcred-roles.md" >> apoctl-appcred.md

echo >> apoctl-appcred.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/terms/docs/appcred-subnets.md" >> apoctl-appcred.md

echo >> apoctl-appcred.md

pandoc apoctl-appcred.md -o apoctl-appcred.adoc

cat << EOF > appcred.adoc

// WE PULL THIS CONTENT FROM https://github.com/aporeto-inc/apoctl
// DO NOT EDIT THIS FILE.
// YOU MUST SUBMIT A PR AGAINST THE UPSTREAM REPO.
// THE UPSTREAM REPO IS CURRENTLY PRIVATE.

$(< apoctl-appcred.adoc)

EOF

rm -f apoctl-appcred.md
rm -f apoctl-appcred.adoc
rm -f apoctl/appcred.adoc
mv appcred.adoc apoctl/appcred.adoc

echo "Getting apoctl auth command"

curl --silent -o apoctl-auth.md -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/terms/docs/auth.md"

echo >> apoctl-auth.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/terms/docs/auth-aporeto.md" >> apoctl-auth.md

echo >> apoctl-auth.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/terms/docs/auth-appcred.md" >> apoctl-auth.md

echo >> apoctl-auth.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/terms/docs/auth-awssts.md" >> apoctl-auth.md

echo >> apoctl-auth.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/terms/docs/auth-azure.md" >> apoctl-auth.md

echo >> apoctl-auth.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/terms/docs/auth-cert.md" >> apoctl-auth.md

echo >> apoctl-auth.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/terms/docs/auth-gcp.md" >> apoctl-auth.md

echo >> apoctl-auth.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/terms/docs/auth-google.md" >> apoctl-auth.md

echo >> apoctl-auth.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/terms/docs/auth-ldap.md" >> apoctl-auth.md

echo >> apoctl-auth.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/terms/docs/auth-oidc.md" >> apoctl-auth.md

echo >> apoctl-auth.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/terms/docs/auth-pcc.md" >> apoctl-auth.md

echo >> apoctl-auth.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/terms/docs/auth-pcc-token.md" >> apoctl-auth.md

echo >> apoctl-auth.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/terms/docs/auth-saml.md" >> apoctl-auth.md

echo >> apoctl-auth.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/terms/docs/auth-token.md" >> apoctl-auth.md

echo >> apoctl-auth.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/terms/docs/auth-verify.md" >> apoctl-auth.md

echo >> apoctl-auth.md

pandoc apoctl-auth.md -o apoctl-auth.adoc

cat << EOF > auth.adoc

// WE PULL THIS CONTENT FROM https://github.com/aporeto-inc/apoctl
// DO NOT EDIT THIS FILE.
// YOU MUST SUBMIT A PR AGAINST THE UPSTREAM REPO.
// THE UPSTREAM REPO IS CURRENTLY PRIVATE.

$(< apoctl-auth.adoc)

EOF

rm -f apoctl-auth.md
rm -f apoctl-auth.adoc
rm -f apoctl-auth.adoc
mv auth.adoc apoctl/auth.adoc

echo "Getting apoctl stats command"

curl --silent -o apoctl-stats.md -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/terms/docs/stats.md"

echo >> apoctl-stats.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/terms/docs/stats-info.md" >> apoctl-stats.md

echo >> apoctl-stats.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/terms/docs/stats-query.md" >> apoctl-stats.md

echo >> apoctl-stats.md

pandoc apoctl-stats.md -o apoctl-stats.adoc

cat << EOF > stats.adoc

// WE PULL THIS CONTENT FROM https://github.com/aporeto-inc/apoctl
// DO NOT EDIT THIS FILE.
// YOU MUST SUBMIT A PR AGAINST THE UPSTREAM REPO.
// THE UPSTREAM REPO IS CURRENTLY PRIVATE.

$(< apoctl-stats.adoc)

EOF

rm -f apoctl-stats.md
rm -f apoctl-stats.adoc
rm -f apoctl-stats.adoc
mv stats.adoc apoctl/stats.adoc

echo "Getting apoctl reports command"

curl --silent -o apoctl-reports.md -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/terms/docs/reports.md"

echo >> apoctl-reports.md

curl -sS -H "Authorization: token ${GITHUB_TOKEN}" \
  "https://raw.githubusercontent.com/aporeto-inc/apoctl/terms/docs/compliance.md" >> apoctl-reports.md

echo >> apoctl-reports.md

pandoc apoctl-reports.md -o apoctl-reports.adoc

cat << EOF > reports.adoc

// WE PULL THIS CONTENT FROM https://github.com/aporeto-inc/apoctl
// DO NOT EDIT THIS FILE.
// YOU MUST SUBMIT A PR AGAINST THE UPSTREAM REPO.
// THE UPSTREAM REPO IS CURRENTLY PRIVATE.

$(< apoctl-reports.adoc)

EOF

rm -f apoctl-reports.md
rm -f apoctl-reports.adoc
rm -f apoctl-reports.adoc
mv reports.adoc apoctl/reports.adoc
